export { getAppStore, registerAppStore } from "./app-store-ref";
export { makeStore, type AppDispatch, type AppStore } from "./store";
export type { RootState } from "./root-reducer";
export { useAppDispatch, useAppSelector } from "./hooks";
export { createAppAsyncThunk } from "./create-app-async-thunk";
export {
  authSlice,
  logout,
  clearLoginError,
  clearAuthError,
  clearRegisterError,
  clearRequestPasswordResetError,
  clearVerifyPasswordResetOtpError,
  clearCompletePasswordResetError,
  onLogin,
  onRegister,
  onRequestPasswordReset,
  onVerifyPasswordResetOtp,
  onCompletePasswordReset,
  login,
  register,
  requestPasswordReset,
  verifyPasswordResetOtp,
  completePasswordReset,
  selectAuth,
  selectLoginStatus,
  selectLoginError,
  selectLoginResponse,
  selectIsAuthenticated,
  selectIsAuthLoading,
  selectRegisterError,
  selectRegisterLoading,
  selectRegisterResponse,
  selectRequestPasswordResetError,
  selectRequestPasswordResetLoading,
  selectRequestPasswordResetResponse,
  selectVerifyPasswordResetOtpError,
  selectVerifyPasswordResetOtpLoading,
  selectVerifyPasswordResetOtpResponse,
  selectCompletePasswordResetError,
  selectCompletePasswordResetLoading,
  selectIsPasswordResetComplete,
  selectAuthStatus,
  selectAuthError,
  type AuthSliceState,
} from "./slices/Auth";
export {
  hydrationSlice,
  clearHydrationErrors,
  onMyWaterIntakeToday,
  onMyWaterIntakeHistory,
  onLogWaterIntake,
  fetchMyWaterIntakeToday,
  fetchMyWaterIntakeHistory,
  logWaterIntake,
  selectHydration,
  selectMyWaterIntakeToday,
  selectMyWaterIntakeTodayStatus,
  selectMyWaterIntakeTodayError,
  selectMyWaterIntakeTodayLoading,
  selectMyWaterIntakeHistory,
  selectMyWaterIntakeHistoryStatus,
  selectMyWaterIntakeHistoryError,
  selectMyWaterIntakeHistoryLoading,
  selectLogWaterIntakeStatus,
  selectLogWaterIntakeError,
  selectIsLoggingWaterIntake,
  selectHydrationTotalMl,
  selectHydrationTargetMl,
  type HydrationSliceState,
  type LogWaterIntakeThunkArgs,
} from "./slices/Hydration";
export {
  workoutSlice,
  clearWorkoutErrors,
  onTodayWorkoutTemplate,
  fetchTodayWorkoutTemplate,
  selectWorkout,
  selectTodayWorkoutTemplate,
  selectTodayWorkoutTemplateStatus,
  selectTodayWorkoutTemplateError,
  selectTodayWorkoutTemplateLoading,
  selectIsWorkoutRestDay,
  type WorkoutSliceState,
  type WorkoutTemplateGql,
} from "./slices/Workout";
export {
  modalSlice,
  selectModals,
  type ModalSize,
  type OpenModalPayload,
  type SingleModalProps,
} from "./slices/modal";
export { CloseModal, closeModal } from "./close-modal";
